export const PROGRAM_GET_REQUEST = 'PROGRAM_GET_REQUEST'
export const PROGRAM_GET_SUCCESS = 'PROGRAM_GET_SUCCESS'
export const PROGRAM_GET_FAIL = 'PROGRAM_GET_FAIL'

export const STUDENT_COURSE_GET_REQUEST = 'STUDENT_COURSE_GET_REQUEST'
export const STUDENT_COURSE_GET_SUCCESS = 'STUDENT_COURSE_GET_SUCCESS'
export const STUDENT_COURSE_GET_FAIL = 'STUDENT_COURSE_GET_FAIL'

export const PROFESSIONAL_COURSE_GET_REQUEST = 'PROFESSIONAL_COURSE_GET_REQUEST'
export const PROFESSIONAL_COURSE_GET_SUCCESS = 'PROFESSIONAL_COURSE_GET_SUCCESS'
export const PROFESSIONAL_COURSE_GET_FAIL = 'PROFESSIONAL_COURSE_GET_FAIL'
